spring.application.name=GuiaSafra

server.error.include-stacktrace=never
server.error.include-message=always

# variavel de ambiente para deploy...
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL}
spring.datasource.username=${DB_USERNAME:seu_rm_fiap}
spring.datasource.password=${DB_PASSWORD:sua_senha_fiap}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# API externa de clima (Open-Meteo).
climate.api.base-url=https://api.open-meteo.com/v1/forecast
climate.api.default-latitude=-23.55
climate.api.default-longitude=-46.63
