-- =====================================================================
-- GLOBAL SOLUTION 2026/1 - FIAP - 2TDS
-- Projeto: Monitoramento agricola inteligente para pequenos e medios
--          produtores. Combina sensores de campo (ESP32/IoT) com previsao
--          climatica derivada de satelite, automatizando alertas e rega
--          por meio de inteligencia no banco (PL/SQL).
--
-- Arquivo: gs_agromonitor_completo.sql  (script unico: roda do inicio ao fim)
-- Conteudo: DDL + Procedures + Carga + Automacao (trigger/procedures) +
--           Function + Relatorios (cursores e JOIN).
-- Banco:   Oracle (compativel com o ambiente da FIAP)
--
-- ORDEM DE EXECUCAO:
--   1) Limpeza e DDL
--   2) Procedures de insercao (SP_INSERT_*)
--   3) Blocos anonimos de carga (80+ registros)
--   4) Automacao: package + trigger (rega de emergencia / alerta de geada)
--   5) Function de apoio
--   6) Relatorios com cursores explicitos e JOIN
--
-- CONVENCOES (alinhadas ao script da sprint anterior - ClyvoCare):
--   - Prefixos: TB_CAD_ (cadastro)  |  TB_MON_ (monitoramento/operacao)
--   - PK: NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
--   - Atributos em INGLES (evita @Column no JPA do Java)
--   - CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
--   - Constraints nomeadas: FK_, UK_, CK_
--   - Texto de PL/SQL e mensagens em PORTUGUES humanizado
--
-- DOMINIOS DE APLICACAO (separacao na camada de aplicacao, nao no banco):
--   C#  (Cadastro) -> escreve TB_CAD_SPECIES, TB_CAD_SLOT
--   Java (Operacao)-> escreve TB_CAD_USER, TB_MON_CLIMATE_FORECAST,
--                     TB_MON_READING, TB_MON_WATERING_EVENT, TB_MON_ALERT;
--                     le TB_CAD_SLOT (somente leitura, para validar FK)
--   O banco e um schema unico; a FK entre dominios e garantida pelo Oracle.
-- =====================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;
SET LINESIZE 200;

-- ---------------------------------------------------------------------
-- LIMPEZA (ignore erros na primeira execucao)
-- ---------------------------------------------------------------------
BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables
        WHERE table_name IN (
            'TB_MON_ALERT','TB_MON_WATERING_EVENT','TB_MON_READING',
            'TB_MON_CLIMATE_FORECAST','TB_MON_ERROR_LOG','TB_MON_RAW_TELEMETRY',
            'TB_CAD_SLOT','TB_CAD_SPECIES','TB_CAD_USER'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- =====================================================================
-- DOMINIO C# (CADASTRO) -- tabelas mais simples
-- =====================================================================

-- SPECIES: catalogo de culturas. Guarda a REGRA de negocio (faixas ideais).
CREATE TABLE TB_CAD_SPECIES (
    ID             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    COMMON_NAME    VARCHAR2(80)  NOT NULL UNIQUE,
    SCIENTIFIC_NAME VARCHAR2(120),
    MIN_HUMIDITY   NUMBER(5,2)   NOT NULL,   -- % minima de umidade tolerada
    MAX_HUMIDITY   NUMBER(5,2)   NOT NULL,   -- % maxima de umidade tolerada
    FROST_MIN_TEMP NUMBER(4,1),              -- temp (C) abaixo da qual ha risco de geada
    WATERING_ML    NUMBER(6)     NOT NULL,   -- volume de agua por rega (ml)
    CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CK_SPECIES_MIN_HUM CHECK (MIN_HUMIDITY BETWEEN 0 AND 100),
    CONSTRAINT CK_SPECIES_MAX_HUM CHECK (MAX_HUMIDITY BETWEEN 0 AND 100),
    CONSTRAINT CK_SPECIES_RANGE   CHECK (MIN_HUMIDITY < MAX_HUMIDITY),
    CONSTRAINT CK_SPECIES_ML      CHECK (WATERING_ML > 0)
);

-- SLOT: cada vaga de plantio monitorada. FILHO de SPECIES (relacao 1:N).
-- Atende o requisito do .NET "pelo menos um relacionamento 1:N".
-- Remocao e LOGICA (campo STATUS), preservando o historico de leituras.
CREATE TABLE TB_CAD_SLOT (
    ID          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    SPECIES_ID  NUMBER(19)   NOT NULL,
    POSITION    VARCHAR2(20) NOT NULL,        -- ex.: "A1", "B3"
    PLANTED_AT  DATE         DEFAULT SYSDATE NOT NULL,
    STATUS      VARCHAR2(15) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_SLOT_SPECIES FOREIGN KEY (SPECIES_ID) REFERENCES TB_CAD_SPECIES(ID),
    CONSTRAINT CK_SLOT_STATUS  CHECK (STATUS IN ('ACTIVE','INACTIVE','HARVESTED'))
);


-- USER: produtores/operadores que acessam pelo app (autenticacao JWT no Java).
CREATE TABLE TB_CAD_USER (
    ID            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR2(100) NOT NULL,
    EMAIL         VARCHAR2(120) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,     -- hash BCrypt; nunca senha pura
    ROLE          VARCHAR2(15)  DEFAULT 'PRODUCER' NOT NULL,
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CK_USER_ROLE CHECK (ROLE IN ('PRODUCER','ADMIN'))
);

-- CLIMATE_FORECAST: dado vindo da API externa de clima (derivada de satelite).
-- Guarda SO os campos que a regra de negocio usa. O JSON cru vai para a
-- colecao NoSQL (exemplo NoSQL exigido na pag. 44).
CREATE TABLE TB_MON_CLIMATE_FORECAST (
    ID             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    FORECAST_DATE  DATE          NOT NULL,    -- dia a que a previsao se refere
    MIN_TEMP       NUMBER(4,1),
    MAX_TEMP       NUMBER(4,1),
    RAINFALL_MM    NUMBER(6,2),               -- precipitacao prevista (mm)
    FROST_PROB     NUMBER(5,2),               -- probabilidade de geada (0 a 100)
    SOURCE         VARCHAR2(40) DEFAULT 'CLIMATE_API' NOT NULL,
    CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CK_FORECAST_FROST CHECK (FROST_PROB BETWEEN 0 AND 100),
    CONSTRAINT CK_FORECAST_TEMP  CHECK (MIN_TEMP <= MAX_TEMP)
);

-- READING: historico de medicoes do sensor.
-- *** CHAVE COMPOSTA *** (SLOT_ID, READ_TIMESTAMP) -> requisito do Java (pag. 32).
-- E a unica tabela que foge do padrao IDENTITY de propósito: sua identidade
-- e naturalmente o par "qual slot + em que momento". No Java vira um
-- @Embeddable ReadingId usado como @EmbeddedId (cobre chave composta E Embedded).
CREATE TABLE TB_MON_READING (
    SLOT_ID        NUMBER(19)   NOT NULL,
    READ_TIMESTAMP TIMESTAMP    NOT NULL,
    HUMIDITY       NUMBER(5,2)  NOT NULL,
    TEMPERATURE    NUMBER(4,1),
    CONSTRAINT PK_READING       PRIMARY KEY (SLOT_ID, READ_TIMESTAMP),
    CONSTRAINT CK_READING_HUM   CHECK (HUMIDITY BETWEEN 0 AND 100),
    CONSTRAINT FK_READING_SLOT  FOREIGN KEY (SLOT_ID) REFERENCES TB_CAD_SLOT(ID)
);

-- WATERING_EVENT: registro de cada acionamento da bomba.
-- ORIGIN distingue rega MANUAL (produtor pelo app) de AUTOMATIC (regra do banco).
-- USER_ID e NULO quando a rega foi automatica (ninguem acionou).
CREATE TABLE TB_MON_WATERING_EVENT (
    ID          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    SLOT_ID     NUMBER(19)   NOT NULL,
    USER_ID     NUMBER(19),                   -- NULL = rega automatica
    ORIGIN      VARCHAR2(12) NOT NULL,
    VOLUME_ML   NUMBER(6)    NOT NULL,
    EVENT_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_WATERING_ORIGIN CHECK (ORIGIN IN ('MANUAL','AUTOMATIC')),
    CONSTRAINT CK_WATERING_ML     CHECK (VOLUME_ML > 0),
    CONSTRAINT FK_WATERING_SLOT   FOREIGN KEY (SLOT_ID) REFERENCES TB_CAD_SLOT(ID),
    CONSTRAINT FK_WATERING_USER   FOREIGN KEY (USER_ID) REFERENCES TB_CAD_USER(ID)
);

-- ALERT: avisos GERADOS pela logica PL/SQL (nao importados da API).
-- Nascem de umidade critica (sensor) ou risco de geada (previsao climatica).
CREATE TABLE TB_MON_ALERT (
    ID          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    SLOT_ID     NUMBER(19)    NOT NULL,
    ALERT_TYPE  VARCHAR2(20)  NOT NULL,        -- ex.: LOW_HUMIDITY, FROST_RISK
    SEVERITY    VARCHAR2(10)  NOT NULL,
    MESSAGE     VARCHAR2(200),
    ALERT_TIME  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    RESOLVED    CHAR(1)       DEFAULT 'N' NOT NULL,
    CONSTRAINT CK_ALERT_SEVERITY CHECK (SEVERITY IN ('LOW','MEDIUM','CRITICAL')),
    CONSTRAINT CK_ALERT_RESOLVED CHECK (RESOLVED IN ('S','N')),
    CONSTRAINT FK_ALERT_SLOT     FOREIGN KEY (SLOT_ID) REFERENCES TB_CAD_SLOT(ID)
);

-- ERROR_LOG: registro das excecoes tratadas nas procedures de carga (PL/SQL).
CREATE TABLE TB_MON_ERROR_LOG (
    ID              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PROCEDURE_NAME  VARCHAR2(100),
    USER_NAME       VARCHAR2(100),
    OCCURRENCE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    ERROR_CODE      VARCHAR2(20),
    ERROR_MESSAGE   VARCHAR2(2000)
);

-- ---------------------------------------------------------------------
-- INDICES de apoio (consultas mais comuns dos relatorios e da logica)
-- ---------------------------------------------------------------------
CREATE INDEX IX_READING_TIME    ON TB_MON_READING (READ_TIMESTAMP);
CREATE INDEX IX_WATERING_SLOT   ON TB_MON_WATERING_EVENT (SLOT_ID);
CREATE INDEX IX_ALERT_SLOT_RES  ON TB_MON_ALERT (SLOT_ID, RESOLVED);
CREATE INDEX IX_FORECAST_DATE   ON TB_MON_CLIMATE_FORECAST (FORECAST_DATE);

COMMIT;

-- #####################################################################
-- # 2) PROCEDURES DE INSERCAO
-- #   Padrao: cada procedure trata uma excecao especifica de dominio,
-- #   uma de valor, e WHEN OTHERS. Erros vao para TB_MON_ERROR_LOG.
-- #   Mensagens em portugues humanizado.
-- #####################################################################

-- Procedure: inserir especie (cultura)
CREATE OR REPLACE PROCEDURE SP_INSERT_SPECIES(
    p_common_name     IN VARCHAR2,
    p_scientific_name IN VARCHAR2,
    p_min_humidity    IN NUMBER,
    p_max_humidity    IN NUMBER,
    p_frost_min_temp  IN NUMBER,
    p_watering_ml     IN NUMBER
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
    v_user VARCHAR2(100) := USER;
BEGIN
    INSERT INTO TB_CAD_SPECIES
        (COMMON_NAME, SCIENTIFIC_NAME, MIN_HUMIDITY, MAX_HUMIDITY, FROST_MIN_TEMP, WATERING_ML)
    VALUES
        (p_common_name, p_scientific_name, p_min_humidity, p_max_humidity, p_frost_min_temp, p_watering_ml);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'Cultura ja cadastrada: '||p_common_name;
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SPECIES',v_user,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados invalidos para a cultura: '||p_common_name;
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SPECIES',v_user,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SPECIES',v_user,v_code,v_msg);
        COMMIT;
END;
/

-- Procedure: inserir slot (vaga de plantio)
CREATE OR REPLACE PROCEDURE SP_INSERT_SLOT(
    p_species_id IN NUMBER,
    p_position   IN VARCHAR2,
    p_planted_at IN DATE
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
    v_user VARCHAR2(100) := USER;
BEGIN
    INSERT INTO TB_CAD_SLOT (SPECIES_ID, POSITION, PLANTED_AT)
    VALUES (p_species_id, p_position, p_planted_at);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'Slot duplicado na posicao: '||p_position;
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SLOT',v_user,v_code,v_msg);
        COMMIT;
    WHEN INVALID_NUMBER THEN
        v_code := SQLCODE;
        v_msg  := 'ID de cultura invalido para o slot na posicao: '||p_position;
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SLOT',v_user,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SLOT',v_user,v_code,v_msg);
        COMMIT;
END;
/

-- Procedure: inserir usuario (produtor/operador)
CREATE OR REPLACE PROCEDURE SP_INSERT_USER(
    p_name          IN VARCHAR2,
    p_email         IN VARCHAR2,
    p_password_hash IN VARCHAR2,
    p_role          IN VARCHAR2
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
    v_user VARCHAR2(100) := USER;
BEGIN
    INSERT INTO TB_CAD_USER (NAME, EMAIL, PASSWORD_HASH, ROLE)
    VALUES (p_name, p_email, p_password_hash, p_role);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'Email ja cadastrado: '||p_email;
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_USER',v_user,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados invalidos para o usuario: '||p_name;
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_USER',v_user,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_USER',v_user,v_code,v_msg);
        COMMIT;
END;
/

-- Procedure: inserir previsao climatica (vinda da API de satelite)
CREATE OR REPLACE PROCEDURE SP_INSERT_FORECAST(
    p_forecast_date IN DATE,
    p_min_temp      IN NUMBER,
    p_max_temp      IN NUMBER,
    p_rainfall_mm   IN NUMBER,
    p_frost_prob    IN NUMBER,
    p_source        IN VARCHAR2
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
    v_user VARCHAR2(100) := USER;
BEGIN
    INSERT INTO TB_MON_CLIMATE_FORECAST
        (FORECAST_DATE, MIN_TEMP, MAX_TEMP, RAINFALL_MM, FROST_PROB, SOURCE)
    VALUES
        (p_forecast_date, p_min_temp, p_max_temp, p_rainfall_mm, p_frost_prob, p_source);
    COMMIT;
EXCEPTION
    WHEN INVALID_NUMBER THEN
        v_code := SQLCODE;
        v_msg  := 'Valor numerico invalido na previsao de '||TO_CHAR(p_forecast_date,'DD/MM/YYYY');
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_FORECAST',v_user,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados invalidos na previsao climatica';
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_FORECAST',v_user,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_FORECAST',v_user,v_code,v_msg);
        COMMIT;
END;
/

-- Procedure: inserir leitura do sensor (chave composta SLOT_ID + READ_TIMESTAMP)
-- E o INSERT nesta tabela que dispara a trigger de automacao (secao 4).
CREATE OR REPLACE PROCEDURE SP_INSERT_READING(
    p_slot_id        IN NUMBER,
    p_read_timestamp IN TIMESTAMP,
    p_humidity       IN NUMBER,
    p_temperature    IN NUMBER
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
    v_user VARCHAR2(100) := USER;
BEGIN
    INSERT INTO TB_MON_READING (SLOT_ID, READ_TIMESTAMP, HUMIDITY, TEMPERATURE)
    VALUES (p_slot_id, p_read_timestamp, p_humidity, p_temperature);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'Leitura duplicada para o slot '||p_slot_id||' em '
                  ||TO_CHAR(p_read_timestamp,'DD/MM/YYYY HH24:MI:SS');
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_READING',v_user,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Valor de umidade ou temperatura invalido para o slot '||p_slot_id;
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_READING',v_user,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_READING',v_user,v_code,v_msg);
        COMMIT;
END;
/

-- Procedure: registrar evento de rega (manual ou automatica)
-- p_user_id pode ser NULL quando a rega e automatica.
CREATE OR REPLACE PROCEDURE SP_INSERT_WATERING(
    p_slot_id   IN NUMBER,
    p_user_id   IN NUMBER,
    p_origin    IN VARCHAR2,
    p_volume_ml IN NUMBER
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
    v_user VARCHAR2(100) := USER;
BEGIN
    INSERT INTO TB_MON_WATERING_EVENT (SLOT_ID, USER_ID, ORIGIN, VOLUME_ML)
    VALUES (p_slot_id, p_user_id, p_origin, p_volume_ml);
    COMMIT;
EXCEPTION
    WHEN INVALID_NUMBER THEN
        v_code := SQLCODE;
        v_msg  := 'ID ou volume invalido no evento de rega do slot '||p_slot_id;
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_WATERING',v_user,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados invalidos no evento de rega do slot '||p_slot_id;
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_WATERING',v_user,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_WATERING',v_user,v_code,v_msg);
        COMMIT;
END;
/

-- Procedure: registrar alerta (gerado pela logica do banco)
CREATE OR REPLACE PROCEDURE SP_INSERT_ALERT(
    p_slot_id    IN NUMBER,
    p_alert_type IN VARCHAR2,
    p_severity   IN VARCHAR2,
    p_message    IN VARCHAR2
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
    v_user VARCHAR2(100) := USER;
BEGIN
    INSERT INTO TB_MON_ALERT (SLOT_ID, ALERT_TYPE, SEVERITY, MESSAGE)
    VALUES (p_slot_id, p_alert_type, p_severity, p_message);
    COMMIT;
EXCEPTION
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados invalidos no alerta do slot '||p_slot_id;
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_ALERT',v_user,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_ALERT',v_user,v_code,v_msg);
        COMMIT;
END;
/

-- #####################################################################
-- # 3) BLOCOS ANONIMOS DE CARGA (80+ registros)
-- #   Inclui leituras criticas propositais para acionar a automacao,
-- #   e um insert duplicado proposital para gerar log de erro.
-- #####################################################################

-- Carga de culturas (especies)
BEGIN
    SP_INSERT_SPECIES('Alface',  'Lactuca sativa',      60, 85,  2, 200);
    SP_INSERT_SPECIES('Tomate',  'Solanum lycopersicum',50, 75,  5, 350);
    SP_INSERT_SPECIES('Cenoura', 'Daucus carota',       55, 80,  0, 250);
    SP_INSERT_SPECIES('Morango', 'Fragaria ananassa',   65, 90,  3, 180);
    SP_INSERT_SPECIES('Batata',  'Solanum tuberosum',   45, 70, -2, 400);
    SP_INSERT_SPECIES('Rucula',  'Eruca sativa',        60, 85,  4, 190);

    -- Insert duplicado proposital (gera log em TB_MON_ERROR_LOG)
    SP_INSERT_SPECIES('Alface',  'Lactuca sativa',      60, 85,  2, 200);
END;
/

-- Carga de slots (vagas de plantio), referenciando as culturas por nome
DECLARE
    v_alface  NUMBER; v_tomate  NUMBER; v_cenoura NUMBER;
    v_morango NUMBER; v_batata  NUMBER; v_rucula  NUMBER;
BEGIN
    SELECT ID INTO v_alface  FROM TB_CAD_SPECIES WHERE COMMON_NAME = 'Alface';
    SELECT ID INTO v_tomate  FROM TB_CAD_SPECIES WHERE COMMON_NAME = 'Tomate';
    SELECT ID INTO v_cenoura FROM TB_CAD_SPECIES WHERE COMMON_NAME = 'Cenoura';
    SELECT ID INTO v_morango FROM TB_CAD_SPECIES WHERE COMMON_NAME = 'Morango';
    SELECT ID INTO v_batata  FROM TB_CAD_SPECIES WHERE COMMON_NAME = 'Batata';
    SELECT ID INTO v_rucula  FROM TB_CAD_SPECIES WHERE COMMON_NAME = 'Rucula';

    SP_INSERT_SLOT(v_alface,  'A1', DATE '2026-03-01');
    SP_INSERT_SLOT(v_tomate,  'A2', DATE '2026-03-05');
    SP_INSERT_SLOT(v_cenoura, 'B1', DATE '2026-02-20');
    SP_INSERT_SLOT(v_morango, 'B2', DATE '2026-03-10');
    SP_INSERT_SLOT(v_batata,  'C1', DATE '2026-02-15');
    SP_INSERT_SLOT(v_rucula,  'C2', DATE '2026-03-12');
    SP_INSERT_SLOT(v_alface,  'D1', DATE '2026-03-15');
    SP_INSERT_SLOT(v_tomate,  'D2', DATE '2026-03-18');
END;
/

-- Carga de usuarios (produtores/operadores)
BEGIN
    SP_INSERT_USER('Joao da Silva',   'joao@fazenda.com',    'hash_bcrypt_1', 'PRODUCER');
    SP_INSERT_USER('Maria Oliveira',  'maria@fazenda.com',   'hash_bcrypt_2', 'PRODUCER');
    SP_INSERT_USER('Carlos Pereira',  'carlos@fazenda.com',  'hash_bcrypt_3', 'PRODUCER');
    SP_INSERT_USER('Admin Sistema',   'admin@agromonitor.com','hash_bcrypt_4','ADMIN');

    -- Insert duplicado proposital (email repetido -> log de erro)
    SP_INSERT_USER('Joao Duplicado',  'joao@fazenda.com',    'hash_bcrypt_x', 'PRODUCER');
END;
/

-- Carga de previsoes climaticas (simulando dados vindos da API de satelite)
BEGIN
    SP_INSERT_FORECAST(DATE '2026-05-20', 12, 24, 0.0,  5, 'CLIMATE_API');
    SP_INSERT_FORECAST(DATE '2026-05-21', 10, 22, 2.5, 15, 'CLIMATE_API');
    SP_INSERT_FORECAST(DATE '2026-05-22',  8, 19, 0.0, 40, 'CLIMATE_API');
    SP_INSERT_FORECAST(DATE '2026-05-23',  3, 14, 0.0, 75, 'CLIMATE_API'); -- risco alto de geada
    SP_INSERT_FORECAST(DATE '2026-05-24',  1, 11, 0.0, 90, 'CLIMATE_API'); -- risco critico de geada
    SP_INSERT_FORECAST(DATE '2026-05-25',  7, 18, 8.0, 20, 'CLIMATE_API');
    SP_INSERT_FORECAST(DATE '2026-05-26', 14, 26, 0.0,  5, 'CLIMATE_API');
    SP_INSERT_FORECAST(DATE '2026-05-27', 15, 28, 1.0,  0, 'CLIMATE_API');
    SP_INSERT_FORECAST(DATE '2026-05-28', 13, 25, 12.0,10, 'CLIMATE_API');
    SP_INSERT_FORECAST(DATE '2026-05-29', 11, 23, 3.0, 25, 'CLIMATE_API');
END;
/

-- Carga de leituras de sensor. Volume principal do dataset.
-- ALGUMAS leituras sao propositalmente CRITICAS (umidade abaixo do minimo
-- da cultura do slot) para que a trigger de automacao reaja na secao 4.
DECLARE
    v_s_a1 NUMBER; v_s_a2 NUMBER; v_s_b1 NUMBER; v_s_b2 NUMBER;
    v_s_c1 NUMBER; v_s_c2 NUMBER; v_s_d1 NUMBER; v_s_d2 NUMBER;
BEGIN
    SELECT ID INTO v_s_a1 FROM TB_CAD_SLOT WHERE POSITION = 'A1';
    SELECT ID INTO v_s_a2 FROM TB_CAD_SLOT WHERE POSITION = 'A2';
    SELECT ID INTO v_s_b1 FROM TB_CAD_SLOT WHERE POSITION = 'B1';
    SELECT ID INTO v_s_b2 FROM TB_CAD_SLOT WHERE POSITION = 'B2';
    SELECT ID INTO v_s_c1 FROM TB_CAD_SLOT WHERE POSITION = 'C1';
    SELECT ID INTO v_s_c2 FROM TB_CAD_SLOT WHERE POSITION = 'C2';
    SELECT ID INTO v_s_d1 FROM TB_CAD_SLOT WHERE POSITION = 'D1';
    SELECT ID INTO v_s_d2 FROM TB_CAD_SLOT WHERE POSITION = 'D2';

    -- Slot A1 (Alface, min 60%): leituras normais e uma critica
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-24 06:00:00', 72, 18);
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-24 12:00:00', 68, 22);
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-24 18:00:00', 64, 20);
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-25 06:00:00', 58, 17);
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-25 12:00:00', 35, 24); -- CRITICA
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-25 18:00:00', 80, 19); -- apos rega

    -- Slot A2 (Tomate, min 50%)
    SP_INSERT_READING(v_s_a2, TIMESTAMP '2026-05-24 06:00:00', 62, 19);
    SP_INSERT_READING(v_s_a2, TIMESTAMP '2026-05-24 12:00:00', 58, 25);
    SP_INSERT_READING(v_s_a2, TIMESTAMP '2026-05-24 18:00:00', 54, 21);
    SP_INSERT_READING(v_s_a2, TIMESTAMP '2026-05-25 12:00:00', 42, 26); -- CRITICA
    SP_INSERT_READING(v_s_a2, TIMESTAMP '2026-05-25 18:00:00', 70, 22);

    -- Slot B1 (Cenoura, min 55%)
    SP_INSERT_READING(v_s_b1, TIMESTAMP '2026-05-24 08:00:00', 70, 16);
    SP_INSERT_READING(v_s_b1, TIMESTAMP '2026-05-24 14:00:00', 66, 20);
    SP_INSERT_READING(v_s_b1, TIMESTAMP '2026-05-25 08:00:00', 61, 17);
    SP_INSERT_READING(v_s_b1, TIMESTAMP '2026-05-25 14:00:00', 59, 19);

    -- Slot B2 (Morango, min 65%): cultura sensivel
    SP_INSERT_READING(v_s_b2, TIMESTAMP '2026-05-24 07:00:00', 78, 15);
    SP_INSERT_READING(v_s_b2, TIMESTAMP '2026-05-24 13:00:00', 72, 21);
    SP_INSERT_READING(v_s_b2, TIMESTAMP '2026-05-25 07:00:00', 68, 16);
    SP_INSERT_READING(v_s_b2, TIMESTAMP '2026-05-25 13:00:00', 48, 23); -- CRITICA

    -- Slot C1 (Batata, min 45%): mais tolerante
    SP_INSERT_READING(v_s_c1, TIMESTAMP '2026-05-24 09:00:00', 60, 14);
    SP_INSERT_READING(v_s_c1, TIMESTAMP '2026-05-24 15:00:00', 55, 18);
    SP_INSERT_READING(v_s_c1, TIMESTAMP '2026-05-25 09:00:00', 50, 15);
    SP_INSERT_READING(v_s_c1, TIMESTAMP '2026-05-25 15:00:00', 47, 17);

    -- Slot C2 (Rucula, min 60%)
    SP_INSERT_READING(v_s_c2, TIMESTAMP '2026-05-24 06:30:00', 74, 18);
    SP_INSERT_READING(v_s_c2, TIMESTAMP '2026-05-24 12:30:00', 69, 23);
    SP_INSERT_READING(v_s_c2, TIMESTAMP '2026-05-25 06:30:00', 63, 19);
    SP_INSERT_READING(v_s_c2, TIMESTAMP '2026-05-25 12:30:00', 38, 25); -- CRITICA

    -- Slot D1 (Alface, min 60%)
    SP_INSERT_READING(v_s_d1, TIMESTAMP '2026-05-24 06:00:00', 71, 17);
    SP_INSERT_READING(v_s_d1, TIMESTAMP '2026-05-24 18:00:00', 66, 20);
    SP_INSERT_READING(v_s_d1, TIMESTAMP '2026-05-25 06:00:00', 62, 18);
    SP_INSERT_READING(v_s_d1, TIMESTAMP '2026-05-25 18:00:00', 67, 19);

    -- Slot D2 (Tomate, min 50%)
    SP_INSERT_READING(v_s_d2, TIMESTAMP '2026-05-24 08:00:00', 64, 20);
    SP_INSERT_READING(v_s_d2, TIMESTAMP '2026-05-24 20:00:00', 59, 18);
    SP_INSERT_READING(v_s_d2, TIMESTAMP '2026-05-25 08:00:00', 56, 21);
    SP_INSERT_READING(v_s_d2, TIMESTAMP '2026-05-25 20:00:00', 52, 19);
END;
/

-- Carga de eventos de rega manuais (produtor acionando pelo app)
DECLARE
    v_s_a1 NUMBER; v_s_b1 NUMBER; v_s_c1 NUMBER; v_s_d1 NUMBER;
    v_u_joao  NUMBER; v_u_maria NUMBER; v_u_carlos NUMBER;
BEGIN
    SELECT ID INTO v_s_a1 FROM TB_CAD_SLOT WHERE POSITION = 'A1';
    SELECT ID INTO v_s_b1 FROM TB_CAD_SLOT WHERE POSITION = 'B1';
    SELECT ID INTO v_s_c1 FROM TB_CAD_SLOT WHERE POSITION = 'C1';
    SELECT ID INTO v_s_d1 FROM TB_CAD_SLOT WHERE POSITION = 'D1';

    SELECT ID INTO v_u_joao   FROM TB_CAD_USER WHERE EMAIL = 'joao@fazenda.com';
    SELECT ID INTO v_u_maria  FROM TB_CAD_USER WHERE EMAIL = 'maria@fazenda.com';
    SELECT ID INTO v_u_carlos FROM TB_CAD_USER WHERE EMAIL = 'carlos@fazenda.com';

    SP_INSERT_WATERING(v_s_a1, v_u_joao,   'MANUAL', 200);
    SP_INSERT_WATERING(v_s_b1, v_u_maria,  'MANUAL', 250);
    SP_INSERT_WATERING(v_s_c1, v_u_carlos, 'MANUAL', 400);
    SP_INSERT_WATERING(v_s_d1, v_u_joao,   'MANUAL', 200);
    SP_INSERT_WATERING(v_s_a1, v_u_maria,  'MANUAL', 200);
END;
/

-- Carga de alguns alertas historicos (antes da automacao)
DECLARE
    v_s_b2 NUMBER; v_s_c2 NUMBER;
BEGIN
    SELECT ID INTO v_s_b2 FROM TB_CAD_SLOT WHERE POSITION = 'B2';
    SELECT ID INTO v_s_c2 FROM TB_CAD_SLOT WHERE POSITION = 'C2';

    SP_INSERT_ALERT(v_s_b2, 'LOW_HUMIDITY', 'MEDIUM',   'Umidade abaixo do ideal no morango');
    SP_INSERT_ALERT(v_s_c2, 'LOW_HUMIDITY', 'LOW',      'Umidade levemente baixa na rucula');
END;
/

-- Carga complementar de leituras (mais dias de historico) para
-- ultrapassar o minimo de 80 registros com dados realistas.
DECLARE
    v_s_a1 NUMBER; v_s_a2 NUMBER; v_s_b1 NUMBER; v_s_b2 NUMBER;
    v_s_c1 NUMBER; v_s_c2 NUMBER; v_s_d1 NUMBER; v_s_d2 NUMBER;
BEGIN
    SELECT ID INTO v_s_a1 FROM TB_CAD_SLOT WHERE POSITION = 'A1';
    SELECT ID INTO v_s_a2 FROM TB_CAD_SLOT WHERE POSITION = 'A2';
    SELECT ID INTO v_s_b1 FROM TB_CAD_SLOT WHERE POSITION = 'B1';
    SELECT ID INTO v_s_b2 FROM TB_CAD_SLOT WHERE POSITION = 'B2';
    SELECT ID INTO v_s_c1 FROM TB_CAD_SLOT WHERE POSITION = 'C1';
    SELECT ID INTO v_s_c2 FROM TB_CAD_SLOT WHERE POSITION = 'C2';
    SELECT ID INTO v_s_d1 FROM TB_CAD_SLOT WHERE POSITION = 'D1';
    SELECT ID INTO v_s_d2 FROM TB_CAD_SLOT WHERE POSITION = 'D2';

    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-20 07:00:00', 65, 14);
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-20 19:00:00', 70, 17);
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-21 07:00:00', 69, 16);
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-21 19:00:00', 65, 24);
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-22 07:00:00', 79, 15);
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-22 19:00:00', 80, 20);
    SP_INSERT_READING(v_s_a2, TIMESTAMP '2026-05-20 07:00:00', 53, 14);
    SP_INSERT_READING(v_s_a2, TIMESTAMP '2026-05-20 19:00:00', 54, 17);
    SP_INSERT_READING(v_s_a2, TIMESTAMP '2026-05-21 07:00:00', 59, 22);
    SP_INSERT_READING(v_s_a2, TIMESTAMP '2026-05-21 19:00:00', 71, 14);
    SP_INSERT_READING(v_s_a2, TIMESTAMP '2026-05-22 07:00:00', 69, 17);
    SP_INSERT_READING(v_s_a2, TIMESTAMP '2026-05-22 19:00:00', 72, 25);
    SP_INSERT_READING(v_s_b1, TIMESTAMP '2026-05-20 07:00:00', 74, 20);
    SP_INSERT_READING(v_s_b1, TIMESTAMP '2026-05-20 19:00:00', 64, 21);
    SP_INSERT_READING(v_s_b1, TIMESTAMP '2026-05-21 07:00:00', 75, 18);
    SP_INSERT_READING(v_s_b1, TIMESTAMP '2026-05-21 19:00:00', 57, 26);
    SP_INSERT_READING(v_s_b1, TIMESTAMP '2026-05-22 07:00:00', 62, 25);
    SP_INSERT_READING(v_s_b1, TIMESTAMP '2026-05-22 19:00:00', 70, 19);
    SP_INSERT_READING(v_s_b2, TIMESTAMP '2026-05-20 07:00:00', 75, 16);
    SP_INSERT_READING(v_s_b2, TIMESTAMP '2026-05-20 19:00:00', 73, 26);
    SP_INSERT_READING(v_s_b2, TIMESTAMP '2026-05-21 07:00:00', 77, 15);
    SP_INSERT_READING(v_s_b2, TIMESTAMP '2026-05-21 19:00:00', 69, 20);
    SP_INSERT_READING(v_s_b2, TIMESTAMP '2026-05-22 07:00:00', 70, 19);
    SP_INSERT_READING(v_s_b2, TIMESTAMP '2026-05-22 19:00:00', 78, 23);
    SP_INSERT_READING(v_s_c1, TIMESTAMP '2026-05-20 07:00:00', 56, 26);
    SP_INSERT_READING(v_s_c1, TIMESTAMP '2026-05-20 19:00:00', 49, 25);
    SP_INSERT_READING(v_s_c1, TIMESTAMP '2026-05-21 07:00:00', 62, 22);
    SP_INSERT_READING(v_s_c1, TIMESTAMP '2026-05-21 19:00:00', 51, 20);
    SP_INSERT_READING(v_s_c1, TIMESTAMP '2026-05-22 07:00:00', 50, 22);
    SP_INSERT_READING(v_s_c1, TIMESTAMP '2026-05-22 19:00:00', 57, 24);
    SP_INSERT_READING(v_s_c2, TIMESTAMP '2026-05-20 07:00:00', 73, 23);
    SP_INSERT_READING(v_s_c2, TIMESTAMP '2026-05-20 19:00:00', 68, 25);
    SP_INSERT_READING(v_s_c2, TIMESTAMP '2026-05-21 07:00:00', 64, 14);
    SP_INSERT_READING(v_s_c2, TIMESTAMP '2026-05-21 19:00:00', 69, 26);
    SP_INSERT_READING(v_s_c2, TIMESTAMP '2026-05-22 07:00:00', 71, 15);
    SP_INSERT_READING(v_s_c2, TIMESTAMP '2026-05-22 19:00:00', 69, 15);
    SP_INSERT_READING(v_s_d1, TIMESTAMP '2026-05-20 07:00:00', 74, 18);
    SP_INSERT_READING(v_s_d1, TIMESTAMP '2026-05-20 19:00:00', 76, 24);
    SP_INSERT_READING(v_s_d1, TIMESTAMP '2026-05-21 07:00:00', 73, 16);
    SP_INSERT_READING(v_s_d1, TIMESTAMP '2026-05-21 19:00:00', 73, 19);
    SP_INSERT_READING(v_s_d1, TIMESTAMP '2026-05-22 07:00:00', 68, 24);
    SP_INSERT_READING(v_s_d1, TIMESTAMP '2026-05-22 19:00:00', 70, 25);
    SP_INSERT_READING(v_s_d2, TIMESTAMP '2026-05-20 07:00:00', 72, 15);
    SP_INSERT_READING(v_s_d2, TIMESTAMP '2026-05-20 19:00:00', 71, 24);
    SP_INSERT_READING(v_s_d2, TIMESTAMP '2026-05-21 07:00:00', 57, 22);
    SP_INSERT_READING(v_s_d2, TIMESTAMP '2026-05-21 19:00:00', 59, 16);
    SP_INSERT_READING(v_s_d2, TIMESTAMP '2026-05-22 07:00:00', 66, 20);
    SP_INSERT_READING(v_s_d2, TIMESTAMP '2026-05-22 19:00:00', 60, 24);
END;
/

-- #####################################################################
-- # 4) AUTOMACAO: FUNCTION + PACKAGE + TRIGGER
-- #   O coracao da solucao. A cada leitura inserida, o banco decide
-- #   sozinho se precisa regar e/ou alertar, cruzando o valor lido com
-- #   a faixa ideal da cultura daquele slot.
-- #####################################################################

-- Function de apoio: classifica a severidade de uma leitura de umidade
-- comparando o valor lido com o minimo tolerado pela cultura.
-- Retorna: 'OK', 'LOW' ou 'CRITICAL'.
CREATE OR REPLACE FUNCTION FN_HUMIDITY_SEVERITY(
    p_humidity IN NUMBER,
    p_min      IN NUMBER
) RETURN VARCHAR2 IS
    v_severity VARCHAR2(10);
    v_gap      NUMBER;
BEGIN
    v_gap := p_min - p_humidity;
    -- Tomada de decisao por faixa de deficit de umidade
    IF v_gap <= 0 THEN
        v_severity := 'OK';            -- dentro ou acima do minimo
    ELSIF v_gap <= 10 THEN
        v_severity := 'LOW';           -- pouco abaixo do minimo
    ELSE
        v_severity := 'CRITICAL';      -- muito abaixo do minimo
    END IF;
    RETURN v_severity;
END;
/

-- Package de automacao agronomica: especificacao (interface publica)
CREATE OR REPLACE PACKAGE PKG_AGRO_AUTOMATION AS
    -- Avalia uma leitura recem-inserida e dispara rega/alerta se necessario.
    -- Chamada pela trigger TRG_READING_AUTOMATION.
    PROCEDURE evaluate_reading(
        p_slot_id   IN NUMBER,
        p_humidity  IN NUMBER
    );

    -- Varre as previsoes de uma data e gera alertas de geada para as
    -- culturas sensiveis (cuja FROST_MIN_TEMP esteja ameacada).
    PROCEDURE check_frost_risk(
        p_forecast_date IN DATE
    );
END PKG_AGRO_AUTOMATION;
/

-- Package de automacao agronomica: corpo (implementacao)
CREATE OR REPLACE PACKAGE BODY PKG_AGRO_AUTOMATION AS

    PROCEDURE evaluate_reading(
        p_slot_id  IN NUMBER,
        p_humidity IN NUMBER
    ) IS
        v_min_humidity TB_CAD_SPECIES.MIN_HUMIDITY%TYPE;
        v_watering_ml  TB_CAD_SPECIES.WATERING_ML%TYPE;
        v_common_name  TB_CAD_SPECIES.COMMON_NAME%TYPE;
        v_severity     VARCHAR2(10);
        v_code         VARCHAR2(20);
        v_user         VARCHAR2(100) := USER;
        v_msg          VARCHAR2(2000);
    BEGIN
        -- Busca a regra da cultura plantada neste slot (tabela -> variaveis)
        SELECT sp.MIN_HUMIDITY, sp.WATERING_ML, sp.COMMON_NAME
          INTO v_min_humidity, v_watering_ml, v_common_name
          FROM TB_CAD_SLOT sl
          JOIN TB_CAD_SPECIES sp ON sp.ID = sl.SPECIES_ID
         WHERE sl.ID = p_slot_id;

        -- Classifica a leitura usando a function de apoio
        v_severity := FN_HUMIDITY_SEVERITY(p_humidity, v_min_humidity);

        -- Decisao de negocio conforme a severidade
        IF v_severity = 'CRITICAL' THEN
            -- Rega automatica de emergencia (USER_ID nulo = acionada pelo sistema)
            INSERT INTO TB_MON_WATERING_EVENT (SLOT_ID, USER_ID, ORIGIN, VOLUME_ML)
            VALUES (p_slot_id, NULL, 'AUTOMATIC', v_watering_ml);

            INSERT INTO TB_MON_ALERT (SLOT_ID, ALERT_TYPE, SEVERITY, MESSAGE)
            VALUES (p_slot_id, 'LOW_HUMIDITY', 'CRITICAL',
                    'Umidade critica em '||v_common_name||' ('||p_humidity
                    ||'%). Rega automatica de '||v_watering_ml||'ml acionada.');
        ELSIF v_severity = 'LOW' THEN
            -- Apenas alerta, sem rega automatica
            INSERT INTO TB_MON_ALERT (SLOT_ID, ALERT_TYPE, SEVERITY, MESSAGE)
            VALUES (p_slot_id, 'LOW_HUMIDITY', 'MEDIUM',
                    'Umidade baixa em '||v_common_name||' ('||p_humidity
                    ||'%). Monitorar de perto.');
        END IF;
        -- Severidade 'OK' nao gera nenhuma acao.
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            -- Slot sem cultura associada: registra no log e nao interrompe a carga
            v_code := SQLCODE;
            INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
            VALUES ('PKG_AGRO_AUTOMATION.evaluate_reading',v_user,v_code,
                    'Slot '||p_slot_id||' sem cultura associada na avaliacao da leitura.');
        WHEN OTHERS THEN
            v_code := SQLCODE;
            v_msg  := SUBSTR(SQLERRM,1,2000);
            INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
            VALUES ('PKG_AGRO_AUTOMATION.evaluate_reading',v_user,v_code,v_msg);
    END evaluate_reading;

    PROCEDURE check_frost_risk(
        p_forecast_date IN DATE
    ) IS
        v_min_temp   TB_MON_CLIMATE_FORECAST.MIN_TEMP%TYPE;
        v_frost_prob TB_MON_CLIMATE_FORECAST.FROST_PROB%TYPE;
        v_count      NUMBER := 0;
        v_code       VARCHAR2(20);
        v_user       VARCHAR2(100) := USER;
        v_msg        VARCHAR2(2000);

        -- Cursor explicito: culturas ativas sensiveis a geada
        CURSOR c_sensitive_slots IS
            SELECT sl.ID AS slot_id, sp.COMMON_NAME, sp.FROST_MIN_TEMP
              FROM TB_CAD_SLOT sl
              JOIN TB_CAD_SPECIES sp ON sp.ID = sl.SPECIES_ID
             WHERE sl.STATUS = 'ACTIVE'
               AND sp.FROST_MIN_TEMP IS NOT NULL;
    BEGIN
        -- Busca a previsao da data informada (tabela -> variaveis)
        SELECT MIN_TEMP, FROST_PROB
          INTO v_min_temp, v_frost_prob
          FROM TB_MON_CLIMATE_FORECAST
         WHERE FORECAST_DATE = p_forecast_date;

        -- Se nao ha risco relevante de geada, encerra sem alertas
        IF v_frost_prob < 50 THEN
            DBMS_OUTPUT.PUT_LINE('Sem risco relevante de geada em '
                ||TO_CHAR(p_forecast_date,'DD/MM/YYYY')
                ||' (probabilidade '||v_frost_prob||'%).');
            RETURN;
        END IF;

        -- Para cada cultura sensivel, verifica se a temperatura ameaca
        FOR reg IN c_sensitive_slots LOOP
            IF v_min_temp <= reg.FROST_MIN_TEMP THEN
                INSERT INTO TB_MON_ALERT (SLOT_ID, ALERT_TYPE, SEVERITY, MESSAGE)
                VALUES (reg.slot_id, 'FROST_RISK', 'CRITICAL',
                        'Risco de geada para '||reg.COMMON_NAME||' em '
                        ||TO_CHAR(p_forecast_date,'DD/MM/YYYY')||'. Minima prevista '
                        ||v_min_temp||'C (limite '||reg.FROST_MIN_TEMP||'C).');
                v_count := v_count + 1;
            END IF;
        END LOOP;

        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Verificacao de geada em '
            ||TO_CHAR(p_forecast_date,'DD/MM/YYYY')||': '
            ||v_count||' alerta(s) gerado(s).');
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Nao ha previsao cadastrada para '
                ||TO_CHAR(p_forecast_date,'DD/MM/YYYY')||'.');
        WHEN OTHERS THEN
            v_code := SQLCODE;
            v_msg  := SUBSTR(SQLERRM,1,2000);
            INSERT INTO TB_MON_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
            VALUES ('PKG_AGRO_AUTOMATION.check_frost_risk',v_user,v_code,v_msg);
    END check_frost_risk;

END PKG_AGRO_AUTOMATION;
/

-- Trigger: a cada nova leitura inserida, aciona a avaliacao automatica.
-- AFTER INSERT FOR EACH ROW: escreve apenas em WATERING_EVENT e ALERT
-- (tabelas distintas de READING), evitando o erro de mutating table.
CREATE OR REPLACE TRIGGER TRG_READING_AUTOMATION
AFTER INSERT ON TB_MON_READING
FOR EACH ROW
BEGIN
    PKG_AGRO_AUTOMATION.evaluate_reading(:NEW.SLOT_ID, :NEW.HUMIDITY);
END;
/

-- ---------------------------------------------------------------------
-- DEMONSTRACAO DA AUTOMACAO
-- As leituras inseridas ANTES da trigger (secao 3) nao a dispararam.
-- Estas novas leituras criticas, inseridas APOS a trigger existir,
-- acionam a rega automatica e os alertas ao vivo.
-- ---------------------------------------------------------------------
DECLARE
    v_s_a1 NUMBER; v_s_b2 NUMBER; v_s_c2 NUMBER;
BEGIN
    SELECT ID INTO v_s_a1 FROM TB_CAD_SLOT WHERE POSITION = 'A1'; -- Alface, min 60
    SELECT ID INTO v_s_b2 FROM TB_CAD_SLOT WHERE POSITION = 'B2'; -- Morango, min 65
    SELECT ID INTO v_s_c2 FROM TB_CAD_SLOT WHERE POSITION = 'C2'; -- Rucula, min 60

    -- Leitura CRITICA (deficit > 10): dispara rega automatica + alerta CRITICAL
    SP_INSERT_READING(v_s_a1, TIMESTAMP '2026-05-26 06:00:00', 30, 21);
    -- Leitura BAIXA (deficit <= 10): dispara apenas alerta MEDIUM
    SP_INSERT_READING(v_s_b2, TIMESTAMP '2026-05-26 06:00:00', 58, 16);
    -- Leitura CRITICA na rucula
    SP_INSERT_READING(v_s_c2, TIMESTAMP '2026-05-26 06:00:00', 33, 22);
END;
/

-- Verificacao de risco de geada para as datas mais frias previstas
BEGIN
    DBMS_OUTPUT.PUT_LINE('===================================================');
    DBMS_OUTPUT.PUT_LINE('   DEMONSTRACAO - VERIFICACAO DE RISCO DE GEADA     ');
    DBMS_OUTPUT.PUT_LINE('===================================================');
    PKG_AGRO_AUTOMATION.check_frost_risk(DATE '2026-05-23');
    PKG_AGRO_AUTOMATION.check_frost_risk(DATE '2026-05-24');
    PKG_AGRO_AUTOMATION.check_frost_risk(DATE '2026-05-26'); -- sem risco, para contraste
END;
/

-- #####################################################################
-- # 5) RELATORIOS COM CURSORES EXPLICITOS E JOIN
-- #   4 cursores explicitos + relatorios gerenciais com JOIN.
-- #   Cada cursor usa estrutura de repeticao e decisao (IF/ELSIF/ELSE).
-- #####################################################################

-- Cursor explicito 1: slots ativos com classificacao de risco hidrico
DECLARE
    CURSOR c_slots_status IS
        SELECT sl.POSITION, sp.COMMON_NAME, sp.MIN_HUMIDITY,
               (SELECT AVG(r.HUMIDITY) FROM TB_MON_READING r WHERE r.SLOT_ID = sl.ID) AS avg_hum
          FROM TB_CAD_SLOT sl
          JOIN TB_CAD_SPECIES sp ON sp.ID = sl.SPECIES_ID
         WHERE sl.STATUS = 'ACTIVE'
         ORDER BY avg_hum;

    v_classification VARCHAR2(20);
    v_count_risk     NUMBER := 0;
    v_count_ok       NUMBER := 0;
    v_total          NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('   CURSOR 1 - RISCO HIDRICO POR SLOT                 ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE(RPAD('Slot',8)||RPAD('Cultura',12)||RPAD('Umid.Media',12)||
        RPAD('Minimo',10)||'Situacao');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',60,'-'));

    FOR reg IN c_slots_status LOOP
        -- Tomada de decisao: comparar media com o minimo da cultura
        IF reg.avg_hum IS NULL THEN
            v_classification := 'Sem leituras';
        ELSIF reg.avg_hum < reg.MIN_HUMIDITY THEN
            v_classification := 'EM RISCO';
            v_count_risk := v_count_risk + 1;
        ELSE
            v_classification := 'Adequado';
            v_count_ok := v_count_ok + 1;
        END IF;

        DBMS_OUTPUT.PUT_LINE(RPAD(reg.POSITION,8)||RPAD(reg.COMMON_NAME,12)||
            RPAD(NVL(TO_CHAR(ROUND(reg.avg_hum,1)),'-'),12)||
            RPAD(reg.MIN_HUMIDITY,10)||v_classification);
        v_total := v_total + 1;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE(RPAD('-',60,'-'));
    DBMS_OUTPUT.PUT_LINE('Total de slots ativos: '||v_total);
    DBMS_OUTPUT.PUT_LINE('  Em risco: '||v_count_risk||'   Adequados: '||v_count_ok);
END;
/

-- Cursor explicito 2: consumo de agua por cultura (rega manual + automatica)
DECLARE
    CURSOR c_water_consumption IS
        SELECT sp.COMMON_NAME,
               COUNT(we.ID) AS total_events,
               NVL(SUM(we.VOLUME_ML),0) AS total_ml,
               SUM(CASE WHEN we.ORIGIN = 'AUTOMATIC' THEN 1 ELSE 0 END) AS auto_events
          FROM TB_CAD_SPECIES sp
          JOIN TB_CAD_SLOT sl ON sl.SPECIES_ID = sp.ID
          LEFT JOIN TB_MON_WATERING_EVENT we ON we.SLOT_ID = sl.ID
         GROUP BY sp.COMMON_NAME
         ORDER BY total_ml DESC;

    v_efficiency VARCHAR2(20);
    v_grand_ml   NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('   CURSOR 2 - CONSUMO DE AGUA POR CULTURA            ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE(RPAD('Cultura',12)||RPAD('Regas',8)||RPAD('Total(ml)',12)||
        RPAD('Automaticas',13)||'Perfil');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',60,'-'));

    FOR reg IN c_water_consumption LOOP
        -- Tomada de decisao: perfil de consumo
        IF reg.total_ml >= 1000 THEN
            v_efficiency := 'Alto consumo';
        ELSIF reg.total_ml >= 400 THEN
            v_efficiency := 'Moderado';
        ELSE
            v_efficiency := 'Baixo';
        END IF;

        DBMS_OUTPUT.PUT_LINE(RPAD(reg.COMMON_NAME,12)||RPAD(reg.total_events,8)||
            RPAD(reg.total_ml,12)||RPAD(reg.auto_events,13)||v_efficiency);
        v_grand_ml := v_grand_ml + reg.total_ml;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE(RPAD('-',60,'-'));
    DBMS_OUTPUT.PUT_LINE('Consumo total de agua: '||v_grand_ml||' ml');
END;
/

-- Cursor explicito 3: historico de alertas com quebra de grupo por severidade
DECLARE
    CURSOR c_alerts IS
        SELECT a.SEVERITY, a.ALERT_TYPE, a.MESSAGE, sl.POSITION, sp.COMMON_NAME,
               TO_CHAR(a.ALERT_TIME,'DD/MM/YYYY HH24:MI') AS when_txt
          FROM TB_MON_ALERT a
          JOIN TB_CAD_SLOT sl ON sl.ID = a.SLOT_ID
          JOIN TB_CAD_SPECIES sp ON sp.ID = sl.SPECIES_ID
         ORDER BY DECODE(a.SEVERITY,'CRITICAL',1,'MEDIUM',2,'LOW',3), a.ALERT_TIME;

    v_current_sev VARCHAR2(10) := NULL;
    v_group_count NUMBER := 0;
    v_grand_total NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('   CURSOR 3 - ALERTAS AGRUPADOS POR SEVERIDADE       ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');

    FOR reg IN c_alerts LOOP
        -- Tomada de decisao: detectar mudanca de grupo (quebra)
        IF v_current_sev IS NULL OR reg.SEVERITY <> v_current_sev THEN
            IF v_current_sev IS NOT NULL THEN
                DBMS_OUTPUT.PUT_LINE('   Subtotal '||v_current_sev||': '||v_group_count);
                DBMS_OUTPUT.PUT_LINE('');
            END IF;
            v_current_sev := reg.SEVERITY;
            v_group_count := 0;
            DBMS_OUTPUT.PUT_LINE('--- Severidade: '||reg.SEVERITY||' ---');
        END IF;

        DBMS_OUTPUT.PUT_LINE('  ['||reg.when_txt||'] '||RPAD(reg.POSITION,5)||
            RPAD(reg.COMMON_NAME,12)||reg.ALERT_TYPE);
        v_group_count := v_group_count + 1;
        v_grand_total := v_grand_total + 1;
    END LOOP;

    -- Subtotal do ultimo grupo
    IF v_current_sev IS NOT NULL THEN
        DBMS_OUTPUT.PUT_LINE('   Subtotal '||v_current_sev||': '||v_group_count);
    END IF;
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('Total geral de alertas: '||v_grand_total);
END;
/

-- Cursor explicito 4: ranking de slots por leituras criticas (uso de WHILE e FETCH)
DECLARE
    CURSOR c_critical IS
        SELECT sl.POSITION, sp.COMMON_NAME, sp.MIN_HUMIDITY,
               COUNT(r.SLOT_ID) AS critical_count
          FROM TB_MON_READING r
          JOIN TB_CAD_SLOT sl ON sl.ID = r.SLOT_ID
          JOIN TB_CAD_SPECIES sp ON sp.ID = sl.SPECIES_ID
         WHERE r.HUMIDITY < sp.MIN_HUMIDITY
         GROUP BY sl.POSITION, sp.COMMON_NAME, sp.MIN_HUMIDITY
         ORDER BY critical_count DESC;

    v_pos      TB_CAD_SLOT.POSITION%TYPE;
    v_name     TB_CAD_SPECIES.COMMON_NAME%TYPE;
    v_min      TB_CAD_SPECIES.MIN_HUMIDITY%TYPE;
    v_count    NUMBER;
    v_rank     NUMBER := 0;
    v_priority VARCHAR2(15);
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('   CURSOR 4 - RANKING DE SLOTS POR LEITURAS CRITICAS ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE(RPAD('Rank',6)||RPAD('Slot',8)||RPAD('Cultura',12)||
        RPAD('Criticas',10)||'Prioridade');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',55,'-'));

    OPEN c_critical;
    -- Uso explicito de FETCH dentro de LOOP ... EXIT WHEN
    LOOP
        FETCH c_critical INTO v_pos, v_name, v_min, v_count;
        EXIT WHEN c_critical%NOTFOUND;

        v_rank := v_rank + 1;
        -- Tomada de decisao: prioridade de manutencao
        IF v_count >= 2 THEN
            v_priority := 'URGENTE';
        ELSIF v_count = 1 THEN
            v_priority := 'Atencao';
        ELSE
            v_priority := 'Normal';
        END IF;

        DBMS_OUTPUT.PUT_LINE(RPAD(v_rank,6)||RPAD(v_pos,8)||RPAD(v_name,12)||
            RPAD(v_count,10)||v_priority);
    END LOOP;
    CLOSE c_critical;

    IF v_rank = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Nenhuma leitura critica registrada.');
    END IF;
END;
/

-- Bloco de relatorios gerenciais com JOIN (fecha os 5 relatorios exigidos)
DECLARE
    -- Variaveis para um WHILE LOOP de exemplo (faixas de umidade)
    v_band       NUMBER := 0;
    v_band_start NUMBER;
    v_band_end   NUMBER;
    v_qty        NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('        RELATORIOS GERENCIAIS COM JOIN               ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');

    -- Relatorio JOIN 1: leituras por cultura (media, minima e maxima)
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Relatorio 1: estatisticas de umidade por cultura ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Cultura',12)||RPAD('Leituras',10)||
        RPAD('Media',8)||RPAD('Min',7)||'Max');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',50,'-'));
    FOR r IN (
        SELECT sp.COMMON_NAME,
               COUNT(rd.SLOT_ID) AS qty,
               ROUND(AVG(rd.HUMIDITY),1) AS avg_h,
               MIN(rd.HUMIDITY) AS min_h,
               MAX(rd.HUMIDITY) AS max_h
          FROM TB_MON_READING rd
          JOIN TB_CAD_SLOT sl ON sl.ID = rd.SLOT_ID
          JOIN TB_CAD_SPECIES sp ON sp.ID = sl.SPECIES_ID
         GROUP BY sp.COMMON_NAME
         ORDER BY avg_h DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.COMMON_NAME,12)||RPAD(r.qty,10)||
            RPAD(r.avg_h,8)||RPAD(r.min_h,7)||r.max_h);
    END LOOP;

    -- Relatorio JOIN 2: eventos de rega por origem
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Relatorio 2: regas por origem (manual x automatica) ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Origem',14)||RPAD('Qtd',8)||'Volume total (ml)');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',45,'-'));
    FOR r IN (
        SELECT we.ORIGIN,
               COUNT(we.ID) AS qty,
               SUM(we.VOLUME_ML) AS total_ml
          FROM TB_MON_WATERING_EVENT we
         GROUP BY we.ORIGIN
         ORDER BY qty DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.ORIGIN,14)||RPAD(r.qty,8)||r.total_ml);
    END LOOP;

    -- Relatorio JOIN 3: regas automaticas com o usuario (LEFT JOIN, mostra NULL)
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Relatorio 3: ultimas regas e responsavel ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Slot',8)||RPAD('Origem',12)||RPAD('Volume',9)||'Responsavel');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',50,'-'));
    FOR r IN (
        SELECT sl.POSITION, we.ORIGIN, we.VOLUME_ML,
               NVL(u.NAME,'(sistema)') AS responsible
          FROM TB_MON_WATERING_EVENT we
          JOIN TB_CAD_SLOT sl ON sl.ID = we.SLOT_ID
          LEFT JOIN TB_CAD_USER u ON u.ID = we.USER_ID
         ORDER BY we.EVENT_TIME DESC
         FETCH FIRST 8 ROWS ONLY
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.POSITION,8)||RPAD(r.ORIGIN,12)||
            RPAD(r.VOLUME_ML,9)||r.responsible);
    END LOOP;

    -- Relatorio JOIN 4: previsoes com risco de geada e culturas afetadas
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Relatorio 4: datas de risco de geada ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Data',12)||RPAD('Min.Temp',10)||RPAD('Prob.Geada',12)||'Culturas em risco');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',60,'-'));
    FOR r IN (
        SELECT TO_CHAR(cf.FORECAST_DATE,'DD/MM/YYYY') AS dt,
               cf.MIN_TEMP, cf.FROST_PROB,
               (SELECT COUNT(*) FROM TB_CAD_SLOT sl2
                  JOIN TB_CAD_SPECIES sp2 ON sp2.ID = sl2.SPECIES_ID
                 WHERE sl2.STATUS = 'ACTIVE'
                   AND sp2.FROST_MIN_TEMP >= cf.MIN_TEMP) AS at_risk
          FROM TB_MON_CLIMATE_FORECAST cf
         WHERE cf.FROST_PROB >= 50
         ORDER BY cf.FORECAST_DATE
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.dt,12)||RPAD(r.MIN_TEMP,10)||
            RPAD(r.FROST_PROB||'%',12)||r.at_risk);
    END LOOP;

    -- Relatorio JOIN 5: alertas por cultura e tipo
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Relatorio 5: alertas por cultura e tipo ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Cultura',12)||RPAD('Tipo',16)||'Qtd');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',40,'-'));
    FOR r IN (
        SELECT sp.COMMON_NAME, a.ALERT_TYPE, COUNT(a.ID) AS qty
          FROM TB_MON_ALERT a
          JOIN TB_CAD_SLOT sl ON sl.ID = a.SLOT_ID
          JOIN TB_CAD_SPECIES sp ON sp.ID = sl.SPECIES_ID
         GROUP BY sp.COMMON_NAME, a.ALERT_TYPE
         ORDER BY sp.COMMON_NAME, qty DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.COMMON_NAME,12)||RPAD(r.ALERT_TYPE,16)||r.qty);
    END LOOP;

    -- Distribuicao de leituras por faixa de umidade (uso de WHILE LOOP)
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Relatorio extra: distribuicao por faixa de umidade ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Faixa',14)||'Leituras');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',28,'-'));
    WHILE v_band < 100 LOOP
        v_band_start := v_band;
        v_band_end   := v_band + 20;
        SELECT COUNT(*) INTO v_qty
          FROM TB_MON_READING
         WHERE HUMIDITY >= v_band_start AND HUMIDITY < v_band_end;
        DBMS_OUTPUT.PUT_LINE(RPAD(v_band_start||'-'||v_band_end||'%',14)||v_qty);
        v_band := v_band + 20;
    END LOOP;
END;
/

-- #####################################################################
-- # 6) MODELAGEM NoSQL (COMPATÍVEL COM ORACLE 19c/12c)
-- #####################################################################

-- Tabela de documentos: telemetria bruta (schema flexivel via JSON)
CREATE TABLE TB_MON_RAW_TELEMETRY (
    ID         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    SOURCE     VARCHAR2(40) NOT NULL,           
    RECEIVED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    PAYLOAD    CLOB, 
    CONSTRAINT CK_PAYLOAD_JSON CHECK (PAYLOAD IS JSON)
);

-- Carga de documentos com formatos DIFERENTES entre si
INSERT INTO TB_MON_RAW_TELEMETRY (SOURCE, PAYLOAD) VALUES (
    'ESP32',
    '{
        "device_id": "esp32-A1",
        "slot": "A1",
        "humidity": 30,
        "temperature": 21,
        "battery_pct": 87,
        "wifi_rssi": -62,
        "firmware": "1.4.2",
        "extra_sensors": { "soil_ph": 6.4, "light_lux": 1200 }
    }'
);

INSERT INTO TB_MON_RAW_TELEMETRY (SOURCE, PAYLOAD) VALUES (
    'ESP32',
    '{
        "device_id": "esp32-C2",
        "slot": "C2",
        "humidity": 33,
        "temperature": 22,
        "battery_pct": 41,
        "wifi_rssi": -78,
        "uptime_hours": 512
    }'
);

INSERT INTO TB_MON_RAW_TELEMETRY (SOURCE, PAYLOAD) VALUES (
    'CLIMATE_API',
    '{
        "provider": "satellite-weather",
        "forecast_date": "2026-05-24",
        "temp": { "min": 1, "max": 11, "unit": "C" },
        "rainfall_mm": 0,
        "frost_probability": 0.90,
        "raw_flags": ["frost_warning", "clear_sky"],
        "satellite_pass": "2026-05-23T22:14:00Z"
    }'
);

COMMIT;

-- Consultas NoSQL: Para Oracle 19c/12c, a extração segura de valores em JSON é via JSON_VALUE
DECLARE
    CURSOR c_devices IS
        SELECT JSON_VALUE(t.PAYLOAD, '$.device_id')   AS device_id,
               JSON_VALUE(t.PAYLOAD, '$.slot')        AS slot,
               JSON_VALUE(t.PAYLOAD, '$.battery_pct') AS battery,
               JSON_VALUE(t.PAYLOAD, '$.wifi_rssi')   AS rssi
          FROM TB_MON_RAW_TELEMETRY t
         WHERE t.SOURCE = 'ESP32';
    v_status VARCHAR2(20);
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('   NoSQL - SAUDE DOS DISPOSITIVOS (extraido do JSON) ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE(RPAD('Device',12)||RPAD('Slot',8)||RPAD('Bateria',10)||RPAD('Sinal',8)||'Status');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',50,'-'));
    FOR reg IN c_devices LOOP
        IF TO_NUMBER(reg.battery) < 50 THEN
            v_status := 'Bateria baixa';
        ELSE
            v_status := 'OK';
        END IF;
        DBMS_OUTPUT.PUT_LINE(RPAD(reg.device_id,12)||RPAD(reg.slot,8)||
            RPAD(reg.battery||'%',10)||RPAD(reg.rssi,8)||v_status);
    END LOOP;
END;
/

-- Consulta NoSQL 2
SELECT t.ID,
       t.SOURCE,
       JSON_VALUE(t.PAYLOAD, '$.provider')          AS provider,
       JSON_VALUE(t.PAYLOAD, '$.frost_probability') AS frost_prob
  FROM TB_MON_RAW_TELEMETRY t
 WHERE t.SOURCE = 'CLIMATE_API'
   AND TO_NUMBER(JSON_VALUE(t.PAYLOAD, '$.frost_probability')) > 0.5;

-- =====================================================================
-- FIM DO SCRIPT
-- =====================================================================
COMMIT;